name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: |
            server/package-lock.json

      - run: npm i -g typescript
      - run: npm i -C server
      - run: tsc -p server
      - run: tsc -p client

      - run: |
          set -euo pipefail
          rm -rf "$APP_NAME" "$APP_NAME.zip"
          mkdir -p "$APP_NAME"
          mkdir -p "$APP_NAME/server"
          cp -r server/dist "$APP_NAME/server/"
          cp -r public "$APP_NAME/"
          cp -r config "$APP_NAME/"
          cp start.bat "$APP_NAME/"
          zip -r "$APP_NAME.zip" "$APP_NAME"

      - uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.REPO_ACCESS }}
          files: ${{ env.APP_NAME }}.zip
